"""Regenerate the fixed heart mesh with Python, NumPy and SciPy.

Equal arc-length outline samples and a relaxed triangular lattice avoid pole
crowding. Convex pairs are merged into quadrilaterals, then mirrored exactly.
Only the generated TypeScript data is needed to build or run the game.
"""
from pathlib import Path
import numpy as np
from scipy.spatial import Delaunay

spacing = 0.23
t = np.linspace(0, np.pi, 4097)
curve = np.column_stack((np.sin(t)**3, (13*np.cos(t)-5*np.cos(2*t)-2*np.cos(3*t)-np.cos(4*t)+2)/16))
arc = np.r_[0, np.cumsum(np.linalg.norm(np.diff(curve, axis=0), axis=1))]
segments = round(arc[-1]/spacing)
outline = np.column_stack([np.interp(np.linspace(0,arc[-1],segments+1),arc,curve[:,k]) for k in range(2)])
outline[[0,-1],0]=0
# Boundary goes clockwise from cleft, around the right lobe, to the tip.
seam_segments=round((outline[0,1]-outline[-1,1])/spacing)
seam=np.column_stack((np.zeros(seam_segments-1),np.linspace(outline[-1,1],outline[0,1],seam_segments+1)[1:-1]))
seam=seam[1:] # Leave room for a full-size triangular cell at the pointed tip.
boundary=np.vstack((outline,seam))

def inside(p):
    x,y=p; result=False
    for a,b in zip(boundary,np.roll(boundary,-1,axis=0)):
        if (a[1]>y)!=(b[1]>y) and x < (b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0]: result=not result
    return result

def distance(p, edges):
    a=edges; ab=np.roll(edges,-1,axis=0)-a
    v=np.clip(np.sum((p-a)*ab,axis=1)/np.sum(ab*ab,axis=1),0,1)
    return np.min(np.linalg.norm(p-a-v[:,None]*ab,axis=1))

interior=[]
for j,y in enumerate(np.arange(-.85,.94,spacing*np.sqrt(3)/2)):
    for x in np.arange(spacing/2+(j%2)*spacing/2,1,spacing):
        p=np.array([x,y])
        if inside(p) and distance(p,boundary)>spacing*.65: interior.append(p)
points=np.vstack((boundary,interior))
fixed=len(boundary)
def triangles():
    return [list(map(int,f)) for f in Delaunay(points).simplices if inside(points[f].mean(axis=0))]
for _ in range(60):
    faces=triangles(); neighbors=[set() for _ in points]
    for f in faces:
        for a in f: neighbors[a].update(set(f)-{a})
    updated=points.copy()
    for i in range(fixed,len(points)):
        target=points[list(neighbors[i])].mean(axis=0)
        updated[i]=points[i]*.6+target*.4
    points=updated
faces=triangles()
# Greedily merge compact convex pairs, preferring smaller cells.
candidates=[]
for i,a in enumerate(faces):
    for j in range(i):
        b=faces[j]
        if len(set(a)&set(b))!=2: continue
        ids=list(set(a+b)); center=points[ids].mean(axis=0)
        ids.sort(key=lambda k: np.arctan2(*(points[k]-center)[::-1]))
        ps=points[ids]; edges=np.roll(ps,-1,axis=0)-ps
        turns=np.cross(edges,np.roll(edges,-1,axis=0))
        if min(turns)<.002: continue
        lengths=np.linalg.norm(edges,axis=1)
        area=abs(np.sum(np.cross(ps,np.roll(ps,-1,axis=0))))/2
        if max(lengths)/min(lengths)>2.1 or area>.050: continue
        angles=turns/(lengths*np.roll(lengths,-1))
        candidates.append((area/(min(angles)**2),i,j,ids))
used=set(); merged=[]
for _,i,j,ids in sorted(candidates):
    if i not in used and j not in used:
        used.update((i,j)); merged.append(ids)
faces=[f for i,f in enumerate(faces) if i not in used]+merged
# The full front patch shares all center-line vertices.
vertices=points.tolist(); mirror={}
for i,(x,y) in enumerate(points):
    if abs(x)<1e-9: mirror[i]=i
    else: mirror[i]=len(vertices); vertices.append([-x,y])
faces+= [[mirror[i] for i in reversed(f)] for f in list(faces)]
rim=list(range(len(outline)))+[mirror[i] for i in range(len(outline)-2,0,-1)]
# Bridge the deepest V with one straight edge. The old cleft becomes an
# interior point; filling its triangle preserves every surrounding face and
# gives each belt row one accessible rectangle instead of two recessed ones.
faces.append([mirror[1], 0, 1])
rim.remove(0)
vertices[0][1] -= 0.04 # Give the new front/back triangles comfortable area.
# One broad kite at the bottom is easier to reveal than two narrow triangles.
tip = len(outline) - 1
tip_faces = [f for f in faces if tip in f]
assert len(tip_faces) == 2 and all(len(f) == 3 for f in tip_faces)
tip_quad = sorted(set(tip_faces[0] + tip_faces[1]))
assert len(tip_quad) == 4
center = np.array([vertices[i] for i in tip_quad]).mean(axis=0)
tip_quad.sort(key=lambda i: np.arctan2(vertices[i][1] - center[1], vertices[i][0] - center[0]))
faces = [f for f in faces if tip not in f] + [tip_quad]
# Each interior edge occurs twice; the outline is the only open boundary.
edges={}
for f in faces:
    for a,b in zip(f,f[1:]+f[:1]):
        edge=tuple(sorted((a,b))); edges[edge]=edges.get(edge,0)+1
assert {e for e,n in edges.items() if n==1} == {tuple(sorted((a,b))) for a,b in zip(rim,rim[1:]+rim[:1])}
assert max(edges.values())==2
rows=['// Generated by scripts/generate-heart.py; coordinates are evenly spaced in the face plane.', 'export const heartPoints: [number, number][] = [']
rows += [f'  [{x:.8f}, {y:.8f}],' for x,y in vertices]
rows += ['];','export const heartFaces: number[][] = [']
rows += ['  ['+', '.join(map(str,f))+'],' for f in faces]
rows += ['];','export const heartRim = ['+', '.join(map(str,rim))+'];','']
Path('lib/heart-mesh.ts').write_text('\n'.join(rows))
print(f'{len(vertices)} vertices, {len(faces)} front cells ({sum(len(f)==3 for f in faces)} triangles), {len(rim)} rim segments')

